# ------------------------------------------------------------------------------
# POSTGRESQL LAB CONFIG (SIMULAÇÃO PRODUÇÃO ADYEN)
# Alinhado com adyen_common.conf e PureST Best Practices
# ------------------------------------------------------------------------------

# --- Conexões e Rede ---
listen_addresses = '*'          #
max_connections = 500           # Produção usa 2000, no lab 500 é ideal para estresse
ssl = off                       # Desativado para o lab focar em I/O puro

# --- Memória (CRÍTICO: Ajustado para o Lab) ---
# Em produção é 198GB, mas no lab mantemos baixo para forçar leitura no PureST
shared_buffers = 1GB            
huge_pages = try
work_mem = 141064kB             #
maintenance_work_mem = 4GB      #
temp_buffers = 256MB            #

# --- Write Ahead Log (WAL) ---
wal_level = logical             #
wal_buffers = 64MB              #
wal_compression = on            #
synchronous_commit = on         # Simula o remote_write usando \sleep no pgbench
wal_sync_method = fdatasync

# --- Checkpoints (Smooth I/O strategy) ---
# Usamos a estratégia da produção de espalhar a escrita ao longo do tempo
checkpoint_timeout = 15min      
max_wal_size = 20GB             
min_wal_size = 1GB              #
checkpoint_completion_target = 0.99 #
checkpoint_warning = 10min

# --- Otimização para Pure Storage (RoCE/RDMA) ---
# Dita que leitura aleatória e sequencial têm o mesmo custo no Flash
random_page_cost = 1.0          
effective_io_concurrency = 32   #
effective_cache_size = 8GB      # Ajustado para escala de lab

# --- Background Writer ---
bgwriter_delay = 200ms
bgwriter_lru_maxpages = 200     #
bgwriter_lru_multiplier = 5.0   #

# --- Monitoramento e Performance ---
track_io_timing = true          #
log_checkpoints = on            #
log_lock_waits = on             #
log_min_duration_statement = 1000 #
log_autovacuum_min_duration = 50 #

# --- Autovacuum Tuning ---
autovacuum_max_workers = 10     #
autovacuum_vacuum_cost_delay = 1ms #
autovacuum_vacuum_cost_limit = 3000 #

# --- Extension Support ---
shared_preload_libraries = 'pg_stat_statements'
